name: Build and Release multi OS

on: 
  push:
    branches:
      - develop

jobs:
  MacOS_Build:
    runs-on: macos-latest
    
    steps:
      - name: Check Repository
        uses: actions/checkout@v2
        with:
          ref: electron

      - name: Install Node.JS
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build on MacOS
        env:
          ELECTRON: true
          

      