name: Build and Release multi OS

on: 
  pull_request:
    types: [closed]
    branches: 
      - development
      - main

jobs:
  build:
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os: [{name: macos-latest, dim: mac}, {name: windows-latest, dim: win}, {name: ubuntu-latest, dim: linux}]
        node-version: [16]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Depedencies and run build
        run: |
          npm ci
          npm run package-${{ matrix.os.dim }}

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os.name }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outpuuts.upload_url }}
          asset_path: ${{ env.ARTIFACTS_PATH }}
          asset_name: ${{ env.ARTIFACTS_NAME }}
          asset_content_type: application/zip